o

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -54,11 +54,11 @@ jobs:
           fetch-depth: 0
       - run: timeout 2m make
       - run: |
-        make clean
-        EXECUTABLES=${{ vars.EXECUTABLES }}
-        for exe in $EXECUTABLES; do
-          if [ ! -x "$exe" ]; then
-            echo "$exe not found or not executable"
-            exit 1
-          fi
-        done
+          make clean
+          EXECUTABLES=${{ vars.EXECUTABLES }}
+          for exe in $EXECUTABLES; do
+            if [ ! -x "$exe" ]; then
+              echo "$exe not found or not executable"
+              exit 1
+            fi
+          done
